# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20170422_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretbox',
            name='likes',
            field=models.ManyToManyField(related_name='like', to='first_app.Register'),
        ),
    ]
