# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('tsd', models.CharField(max_length=45)),
                ('ted', models.CharField(max_length=45)),
                ('username', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='secrets',
            name='fusers',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.DeleteModel(
            name='Secrets',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='fusers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Users'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='joiningTable',
            field=models.ManyToManyField(related_name='joining', to='first_app.Users'),
        ),
    ]
