# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170428_0306'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='travelplan',
            managers=[
                ('run1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='username',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
