# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170428_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='ted',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='tsd',
            field=models.DateField(),
        ),
    ]
