# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170425_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoitments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=45)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=45)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Users')),
            ],
        ),
    ]
