# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_appoitments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoitments',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
