# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:51
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170425_2053'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appoitments',
            managers=[
                ('run1', django.db.models.manager.Manager()),
            ],
        ),
    ]
