# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20170423_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authorAndBook',
            field=models.ManyToManyField(related_name='author_related', to='first_app.Books'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='authorName',
        ),
        migrations.AddField(
            model_name='author',
            name='authorName',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
