# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_books_fofregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='fOfRegister',
        ),
    ]
