# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170421_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
