# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20170422_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretbox',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.Register'),
            preserve_default=False,
        ),
    ]
