var num1=-20;
var num2=10;
var num3=-5;
var num4=0;
var string1="name";
var string2="age";
var string3="gender";
var boolean1=true;
var boolean2=false;
var undefine;
console.log("The First num1 is " + num1);
console.log("The second num2 is " + num2);
console.log("The third num3 is " + num3);
console.log("The fourth num4 is " + num4);
console.log("The First string1 is " + string1);
console.log("The second string2 is " + string2);
console.log("The third string3 is " + string3);
console.log("The First boolean1 is " + boolean1);
console.log("The second boolean2 is " + boolean2);
console.log("The first undefine is " + undefine);