# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secrets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Secret', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Users')),
                ('mlikes', models.ManyToManyField(related_name='rlikes', to='first_app.Users')),
            ],
        ),
    ]
