# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000)),
                ('tsd', models.DateField()),
                ('ted', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Users')),
                ('joiningTable', models.ManyToManyField(related_name='joining', to='first_app.Users')),
            ],
            managers=[
                ('run1', django.db.models.manager.Manager()),
            ],
        ),
    ]
