# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_users_datehired'),
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fusers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Users')),
                ('joiningwish', models.ManyToManyField(related_name='joining', to='first_app.Users')),
            ],
            managers=[
                ('run1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='fusers',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='joiningTable',
        ),
        migrations.DeleteModel(
            name='Travelplan',
        ),
    ]
