# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20170429_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
